### ISSUE TITLE
Downloads overwrite each-other

### ISSUE THREAD

**Issue by FlyingCacti** [alexta69/metube#342] opened 2023-11-16 09:47 UTC
Just noticed that when downloading yt channels with lots of video's there are instances where it does not change the file name to "video.webm", "video (2).webm" etc. if the video title is the same name but the yt video's are different and it just overwrites the previous file.

Just wondering if this could be added as a default as it would be very useful.

**Comment by PikuZheng** [comment] 2023-11-16 13:26
yes it is. So I set the file name template to be "id+title"

**Comment by ArabCoders** [comment] 2023-11-16 20:19
This is the intended behavior i think from yt-dlp, if you want you should include etiher the date or youtube-id in the final filename. Good standard and supported by some new plugins for media players is `YYYYMMDD title [youtube-(id)]`

**Comment by FlyingCacti** [comment] 2023-11-18 05:43
Thank you, makes sense for string types.

**Comment by alexta69** [comment] 2023-12-30 08:12
Functionality related to yt-dlp and not MeTube, closing

**Closed by alexta69** 2023-12-30 08:12 UTC
