### ISSUE TITLE
[Feature Request] Adding list based subscription (Full Channel) downloading

### ISSUE THREAD

**Issue by Gaffers2277** [alexta69/metube#242] opened 2023-03-30 12:34 UTC
Using something like [darkenvy ](https://github.com/darkenvy)/[youtube-dlp-subscriptions](https://github.com/darkenvy/youtube-dlp-subscriptions) and adding a UI Element to add whole channels. Along with channel monitoring with a cron script

**Comment by alexta69** [comment] 2023-03-30 19:33
Duplicate of #113 .

**Closed by alexta69** 2023-03-30 19:33 UTC
