### ISSUE TITLE
I cna't access metube using https (with message "Connetcing to server...") 

### ISSUE THREAD

**Issue by kilo20** [alexta69/metube#478] opened 2024-07-26 07:50 UTC
I installed metube using docker. When I run metube in local network there is no problem. But when I access metube using https, metube don't run, showing message "conneting to server...". I installed authelia to authencicate the metube.

The issue uccurs when I access metube using authelia. But after I empt the cache on browser(regardless safari, chrome, firefox and so on), I can access the metube normally. I use nginx proxy manager.

And using Pirvate Browsing(in safari), Sectet Window mode(in google Chrome) etc, I can access the metube normally. So I suppose that the problem is associated with the cookie. How can I solve the issue?

<img width="1150" alt="screen" src="https://github.com/user-attachments/assets/1a76fdea-cd4e-4a34-998d-988afeb3bf8d">

**Comment by PikuZheng** [comment] 2024-07-26 12:22
config file of nginx please

**Comment by kilo20** [comment] 2024-07-26 12:51
> config file of nginx please

I didn't install nginx. I only installed nginx-proxy-manager using docker. In other words, my https access environment is nginx-proxy-manger + cloudflare DNS + austelia.

**Comment by PikuZheng** [comment] 2024-07-26 14:38
I see. I believe it's related to austelia because I can reproduce this issue. The root cause may be that austelia does not correctly handle the identity authentication of the WSS protocol.
I'm not familiar with this, sorry I can't be of more help :(

**Comment by alexta69** [comment] 2024-12-08 15:03
Fixed in #548

**Closed by alexta69** 2024-12-08 15:03 UTC
