### ISSUE TITLE
Ability to auto download from Channel or video added to Playlist?

### ISSUE THREAD

**Issue by RobCortese** [alexta69/metube#170] opened 2022-08-24 14:30 UTC
I understand how to download playlists and specific videos, but is there an ability to automatically download when someone uploads a video to their channel? Or, an ability to automatically download a video when I add it to a playlist?

**Comment by alexta69** [comment] 2022-08-24 19:55
Duplicate of #113.

**Closed by alexta69** 2022-08-24 19:55 UTC
