### ISSUE TITLE
Cookies Error: YDL_OPTIONS is invalid

### ISSUE THREAD

**Issue by eswiig** [alexta69/metube#420] opened 2024-04-12 14:53 UTC
docker-compose.yml file / portainer stack

   volumes:
      - /home/user/cookies:/cookies
    environment:
      - YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt"}
        
log
Creating download directory (/downloads), state directory (/downloads/.metube), and temp dir (/downloads)
Changing ownership of download and state directories to 1000:1000
Running MeTube as user 1000:1000
YTDL_OPTIONS is invalid

**Comment by PikuZheng** [comment] 2024-04-12 15:14
yml grammatical issue, duplicate of #102

**Closed** 2024-04-12 16:03 UTC

**Comment by eswiig** [comment] 2024-04-13 11:19
- 'YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt"}'
      
this works, but I usually write my YAML with dictionary method instead of list as i prefer it, out of curiosity, can you please help me "convert it: to a dictionary method? (i want to learn).

**Comment by PikuZheng** [comment] 2024-04-13 12:43
```
volumes:
  - /home/user/cookies:/cookies
environment:
  YTDL_OPTIONS: {"cookiefile":"/cookies/cookies.txt"}
```
if you really want to use a dictionary :)

**Comment by eswiig** [comment] 2024-04-13 15:34
Failure
failed to pull images of the stack: validating /data/compose/41/docker-compose.yml: services.metube.environment.YTDL_OPTIONS must be a string, number, boolean or null

**Comment by PikuZheng** [comment] 2024-04-14 01:04
how about
```
environment:
      YTDL_OPTIONS: '{"cookiefile":"/cookies/cookies.txt"}'
```

**Comment by eswiig** [comment] 2024-04-14 11:06
that seems to have worked, thank you so much.
