### ISSUE TITLE
how to download youtube videos as multi-threads mode?

### ISSUE THREAD

**Issue by ShotoZhao** [alexta69/metube#387] opened 2024-01-27 13:04 UTC
how to download youtube videos as multi-threads mode?

**Comment by PikuZheng** [comment] 2024-01-27 13:36
Duplicate of #358

**Comment by ShotoZhao** [comment] 2024-01-28 04:36
> Duplicate of #358 ？

yes, i think so. just want to download some videos simultaneously.

**Comment by alexta69** [comment] 2024-04-12 15:55
Duplicate, closing

**Closed by alexta69** 2024-04-12 15:55 UTC
