### ISSUE TITLE
Feature request: Do not use creation/modification date from youtube upload

### ISSUE THREAD

**Issue by WilliUreta** [alexta69/metube#191] opened 2022-10-28 16:46 UTC
Hi, first of all, very nice bit of software.
Is there a way of setting the creation/modification date from when the donwload is made rather than when the video was uploaded? 
Maybe a toggle somewhere? I know the objective of this software is to make it very simple, but I think it would be a nice addition

**Comment by PikuZheng** [comment] 2022-10-29 00:07
duplicate of #166

**Closed** 2022-10-29 16:04 UTC
